build_master:
  image: registry.gitlab.com/gbraad/ceph-build:c7
  script:
    - mkdir public
    - ./ceph-build.sh master
    - mv /root/rpmbuild/RPMS/x86_64/* ./public
    - mv /root/rpmbuild/SRPMS/* ./public
    - rm ./public/ceph-debuginfo-*
  artifacts:
    paths:
      - public

