pages:
  image: registry.gitlab.com/gbraad/ceph-build:c7
  script:
    - mkdir public
    - ./ceph-build.sh master
    - mv /root/rpmbuild/RPMS/x86_64/* ./public
    - mv /root/rpmbuild/SRPMS/* ./public
    - rm ./public/ceph-debuginfo-*
    - createrepo --database ./public
    - ls ./public/ | ./genindex.sh > ./index.html
    - mv ./index.html ./public
  artifacts:
    paths:
      - public
