image: registry.gitlab.com/gbraad/centos:7

before_script:
  - yum install -y git

build_master:
  script:
    - ./ceph-build.sh master
  artifacts:
    paths:
      - /root/rpmbuild/RPMS/x86_64
      - /root/rpmbuild/SRPMS/