pages:
  image: registry.gitlab.com/gbraad/ceph:c7
  script:
    - mkdir public
    - ./ceph-build.sh master
    - mv /root/rpmbuild/RPMS/x86_64/* ./public
    - mv /root/rpmbuild/SRPMS/* ./public
    - rm ./public/ceph-debuginfo-*
    - createrepo --database ./public
    - mv ceph-master.repo ./public
    - ls ./public/ | ./genindex.sh > ./index.html
    - mv ./index.html ./public
  artifacts:
    paths:
      - public
  when: manual


build_docker_build_c7:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/ceph:c7 ./centos
    - docker push registry.gitlab.com/gbraad/ceph:c7
  only:
    - master
  when: manual

build_docker_base_jewel_f24:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - git clone https://github.com/ceph/ceph-docker.git --depth 1 -b master
    - cd ceph-docker/ceph-releases/jewel/fedora/24/base
    - tar -czh . | docker build -t registry.gitlab.com/gbraad/ceph:jewel-base-f24 -
    - docker push registry.gitlab.com/gbraad/ceph:jewel-base-f24
  only:
    - master
  when: manual

build_docker_daemon_jewel_f24:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - git clone https://github.com/ceph/ceph-docker.git --depth 1 -b master
    - cd ceph-docker/ceph-releases/jewel/fedora/24/daemon
    - docker pull registry.gitlab.com/gbraad/ceph:jewel-base-f24
    - docker tag ceph/base:tag-build-master-jewel-fedora-24 registry.gitlab.com/gbraad/ceph:jewel-base-f24
    - tar -czh . | docker build -t registry.gitlab.com/gbraad/ceph:jewel-daemon-f24 -
    - docker push registry.gitlab.com/gbraad/ceph:jewel-daemon-f24
  only:
    - master
  when: manual
